### PR TITLE
ENH speedup struct perc: don't copy feat vectors

### PR DESCRIPTION
**Pull request by moreymat**
This is a quick n dirty fix to speedup the structured perceptron.
The former code creates a copy of each row as a scipy sparse matrix, which is extremely time- and memory-inefficient.
The proposed changes avoid this by passing the dataset to the update function, which can then pick the feature vectors that are really needed.

### CODE REVIEW

**Comment by kowey** [comment]
Wow, really, that changes things? Is that because you don't use all of the indices in update? Or something subtle? Anyway, merging :-)

**Comment by moreymat** [comment]
Every time you get a row from a scipy matrix and assign it to a variable, a new matrix (representing this row) is created.
As we have lots of them, it has a significant impact (around 30% of the CPU time taken by the learner, from preliminary measures).
From what I gathered from reading the scipy doc and stackoverflow, there is no such thing as passing a pointer or a view to a slice of a matrix.

Now the major bottleneck for structured learning is the decoding algorithm itself (e.g. MST).

**Comment by kowey** [comment]
I bet there's all sorts of room for improvement there with our intermediary
dicts etc

**Comment by kowey** [comment]
Or hmm, maybe not.  Hope it doesn't mean having to dig into depparse.  Then
again, maybe you'll find something that Leif will be happy to get a patch
for?

**Comment by moreymat** [comment]
Preliminary profiling indicates that > 80% cpu is taken by mst, for
structured classifiers. We'll have to dive in, eventually.

**Pull request merged**
